### ISSUE TITLE
Join the forces

### ISSUE THREAD

**Issue by sergiors** [dunglas/doctrine-json-odm#2]
Hi @dunglas! First congratulations!

I have been looking for a project to mapping object/json to work with postgres, but I not found.

I'm working on a project called [taxonomy](https://github.com/sergiors/taxonomy).
I think could join forces.

What do you think?

**Comment by dunglas** [comment]
Nice project! I wasn't aware of it. We need to work together!

**Comment by sergiors** [comment]
@dunglas what do you think about use annotation to mapping objects? (like I did in taxonomy)

Do you have some ideia how I could help you?

**Comment by dunglas** [comment]
@sergiors I don't get the benefit of using annotations. With #5 the library is able to store with any serializable PHP data structure. Validations is a different problem and should be handled by a dedicated lib such as the Symfony Validator Component. But I maybe have missed something.

What would be nice to have is DQL extensions to be able to query data stored in JSON columns. There is already a package providing such extensions (https://github.com/boldtrn/JsonbBundle) but I doesn't seem to be maintained and I don't like the used keywords (I would prefer copy symbols from Postgres or MySQL).

**Comment by sergiors** [comment]
With annotations,  you don't need persist class namespace

```json
{
    "_type": "Dunglas\\DoctrineJsonOdm\\Tests\\Fixtures\\TestBundle\\Entity\\Address",
    "_value": {
        "country": {
            "_type": "Dunglas\\DoctrineJsonOdm\\Tests\\Fixtures\\TestBundle\\Entity\\Country",
            "_value": {"name": "Brazil"}
        }
    }
}
```

With annotations
```json
{
    "country": {
        "name": "Brazil"
    }
}
```

If you change your code, you can keep compatibility (like https://github.com/sergiors/taxonomy/blob/master/tests/Fixture/Phone.php#L18)

and query become more complicated

**Comment by dunglas** [comment]
The first implementation (2795149f7fde615f10710732840747a460ed804c) of this lib was similar but it was using Symfony Property Info to read the PHPDoc instead of specific annotations. However, using this kind of approach as a big limitation. You cannot have collections containing different types of documents like that:

```php

class Blog
{
    public $id;
    public $posts = [];
}

class TextPost
{
    public $foo;
    public $bar;
}

class CookRecipe
{
    public $a;
    public $b;
    public $c;
}

$text = new TextPost();
$recipe = new CookRecipe();

$blog = new Blog();
$blog->posts = [$text, $recipe];
```

Storing types in the document allows to do that easily. However I'm not 100% convinced by storing directly FQN in the database. I was thinking about introducing a `TypeConverter` interface. Implementations of this interface will map PHP types with "sanitized" types to store in DB.

WDYT?

**Comment by sergiors** [comment]
Great ideia!

Do you have ideia how it could be the scheme? Because one time in DB, how know to restore the POPO objects?

```php
/** @Entity */
class Blog
{
    /** @Column @Id */
    public $id;
    /** @Column(type="json_document") */
    public $posts = [];
}

class TextPost
{
    public $foo;
    public $bar;
}

class CookRecipe
{
    public $a;
    public $b;
    public $c;
}

$text = new TextPost();
$recipe = new CookRecipe();

$blog = new Blog();
$blog->posts = [$text, $recipe];
```

column posts sanitized in DB
```
{
    "TextPost": {
        "foo": "",
        "bar": ""
    },
    "CookRecipe": {
        "a": "",
        "b": "",
        "c": ""
    }
}
```

Have any ideia how I can map the JSON indexes?

**Comment by maryo** [comment]
Hi. I've created this bundle https://github.com/vaniocz/doctrine-generic-types which introduces a concept of
- generic types
- type guesser (something simmilar to the type guessing feature inside symfony forms) which gusses the types using PHPDoc (the whole PSR-5 draft is supported).

Unfortunately it is full of mega hyper dirty hacks :(.
This helped us to create generic collection classes like LinkedHashMap and LinkedHashSet (I will add them soon). This is primarily because postgres jsonb type does not care about key order in JSON objects (PHP does in arrays/objects).
We also have prepared a generic JSON serializer which can serialize any PHP value  including circular references (https://github.com/vaniocz/stdlib/blob/master/src/UniversalJsonSerializer.php). Probably something simmilar to your normalizer so there is also a possibility to serialise it and not care about the phpdoc using a different doctrine type.
The next thing is to write the Jsonb extensions. I've already written some of them but they are not public since it is part of a project. I have a plan to create a standalone package.

**Comment by dunglas** [comment]
@maryo thank you very much for your feedback! To make the JSON document easier to query, I've proposer a nicer serialization process in #7.

About your "generic type bundle" and your Serializer, they address the same use cases than the [PropertyInfo](http://symfony.com/blog/new-in-symfony-2-8-propertyinfo-component) and [Serializer](http://symfony.com/doc/current/components/serializer.html) Component of Symfony (disclaimer: I'm the maintainer of those components).

Do you think that it's possible to enhance Symfony component to remove the need of custom third-party libraries and use the one supported directly in the core?
