### ISSUE TITLE
MariaDB 10.2+ Support?

### ISSUE THREAD

**Issue by DubbleClick** [dunglas/doctrine-json-odm#58]
While MariaDB has no native JSON Type, the JSON related API exists. Whether the data is internally stored as JSON or as LONGTEXT is not important to me, therefore the question whether using this bundle with Doctrine 2.6 on MariaDB 10.2+ will work or not.

**Comment by Toflar** [comment]
Doctrine DBAL automatically chooses the right `json` column type for you. So it will work just fine. However, if your storage engine does not have any native JSON support, you won't be able to query on it of course 😄

**Comment by DubbleClick** [comment]
Perfect, MariaDB 10.2+ uses InnoDb as a Storage Engine so that should be alright.

**Comment by bpolaszek** [comment]
@DubbleClick @Toflar MariaDB exposes the same API as Mysql 5.7+ for JSON functions, it just uses LONGTEXT instead of BLOB for storing data under the hood (at the cost of an important performance impact for large JSON objects), regardless of the storage engine. 

So Doctrine DBAL won't complain if you use MariaDb instead of MySQL.

If you want to use JSON functions in Doctrine QueryBuilder, have a look at [syslogic/doctrine-json-functions](https://github.com/ScientaNL/DoctrineJsonFunctions).
