### ISSUE TITLE
Is validation supported?

### ISSUE THREAD

**Issue by tsadiq** [dunglas/doctrine-json-odm#75]
Hey, first of all congrats on this project i've been watching it (and waiting for it ^^') from afar for a while and it looks just great.

So, just to be sure, if i use `@Valid` annotation on my `json_document` property, the whole thing will be validated, right?

**Comment by Toflar** [comment]
I've always wondered why people ask first and only then try... 😄 If you're here because of APIP just go ahead and try!
But I don't see how validation is related to this project. This project provides a new Doctrine type that serializes and deserializes data using the Symfony Serializer component. How that data is set on your entity and whether it's validated or not is entirely your problem 😉

**Comment by tsadiq** [comment]
Ahah, the fact is i just made a few days ago a custom constraint to check the validity of a json object by using DTOs and annotations which work just fine, and i've been spending the last days creating validation object for all the json fields i have in my entities (and i have a bunch 😅). I just want to ensure it won't ruin my efforts if i add this ODM to my project ^^

**Comment by Toflar** [comment]
In the days of git, nothing can really ruin your efforts 😄 I'll close that issue, feel free to reopen or open a new one if you find issues. Good luck 😎 ☘️
